// COMPILER GENERATED CODE
// THIS WILL BE OVERWRITTEN AT EACH GENERATION
// EDIT AT YOUR OWN RISK

using System.Runtime.CompilerServices;
using System.Linq;

namespace SSDQopenECA.Model.GPA
{
    [CompilerGenerated]
    public partial class In_Data
    {
        //Modified by Tapas for Max Entries allowed=200
        public double In_Entry1 { get; set; }
        public double In_Entry2 { get; set; }
        public double In_Entry3 { get; set; }
        public double In_Entry4 { get; set; }
        public double In_Entry5 { get; set; }
        public double In_Entry6 { get; set; }
        public double In_Entry7 { get; set; }
        public double In_Entry8 { get; set; }
        public double In_Entry9 { get; set; }
        public double In_Entry10 { get; set; }
        public double In_Entry11 { get; set; }
        public double In_Entry12 { get; set; }
        public double In_Entry13 { get; set; }
        public double In_Entry14 { get; set; }
        public double In_Entry15 { get; set; }
        public double In_Entry16 { get; set; }
        public double In_Entry17 { get; set; }
        public double In_Entry18 { get; set; }
        public double In_Entry19 { get; set; }
        public double In_Entry20 { get; set; }
        public double In_Entry21 { get; set; }
        public double In_Entry22 { get; set; }
        public double In_Entry23 { get; set; }
        public double In_Entry24 { get; set; }
        public double In_Entry25 { get; set; }
        public double In_Entry26 { get; set; }
        public double In_Entry27 { get; set; }
        public double In_Entry28 { get; set; }
        public double In_Entry29 { get; set; }
        public double In_Entry30 { get; set; }
        public double In_Entry31 { get; set; }
        public double In_Entry32 { get; set; }
        public double In_Entry33 { get; set; }
        public double In_Entry34 { get; set; }
        public double In_Entry35 { get; set; }
        public double In_Entry36 { get; set; }
        public double In_Entry37 { get; set; }
        public double In_Entry38 { get; set; }
        public double In_Entry39 { get; set; }
        public double In_Entry40 { get; set; }
        public double In_Entry41 { get; set; }
        public double In_Entry42 { get; set; }
        public double In_Entry43 { get; set; }
        public double In_Entry44 { get; set; }
        public double In_Entry45 { get; set; }
        public double In_Entry46 { get; set; }
        public double In_Entry47 { get; set; }
        public double In_Entry48 { get; set; }
        public double In_Entry49 { get; set; }
        public double In_Entry50 { get; set; }
        public double In_Entry51 { get; set; }
        public double In_Entry52 { get; set; }
        public double In_Entry53 { get; set; }
        public double In_Entry54 { get; set; }
        public double In_Entry55 { get; set; }
        public double In_Entry56 { get; set; }
        public double In_Entry57 { get; set; }
        public double In_Entry58 { get; set; }
        public double In_Entry59 { get; set; }
        public double In_Entry60 { get; set; }
        public double In_Entry61 { get; set; }
        public double In_Entry62 { get; set; }
        public double In_Entry63 { get; set; }
        public double In_Entry64 { get; set; }
        public double In_Entry65 { get; set; }
        public double In_Entry66 { get; set; }
        public double In_Entry67 { get; set; }
        public double In_Entry68 { get; set; }
        public double In_Entry69 { get; set; }
        public double In_Entry70 { get; set; }
        public double In_Entry71 { get; set; }
        public double In_Entry72 { get; set; }
        public double In_Entry73 { get; set; }
        public double In_Entry74 { get; set; }
        public double In_Entry75 { get; set; }
        public double In_Entry76 { get; set; }
        public double In_Entry77 { get; set; }
        public double In_Entry78 { get; set; }
        public double In_Entry79 { get; set; }
        public double In_Entry80 { get; set; }
        public double In_Entry81 { get; set; }
        public double In_Entry82 { get; set; }
        public double In_Entry83 { get; set; }
        public double In_Entry84 { get; set; }
        public double In_Entry85 { get; set; }
        public double In_Entry86 { get; set; }
        public double In_Entry87 { get; set; }
        public double In_Entry88 { get; set; }
        public double In_Entry89 { get; set; }
        public double In_Entry90 { get; set; }
        public double In_Entry91 { get; set; }
        public double In_Entry92 { get; set; }
        public double In_Entry93 { get; set; }
        public double In_Entry94 { get; set; }
        public double In_Entry95 { get; set; }
        public double In_Entry96 { get; set; }
        public double In_Entry97 { get; set; }
        public double In_Entry98 { get; set; }
        public double In_Entry99 { get; set; }
        public double In_Entry100 { get; set; }
        public double In_Entry101 { get; set; }
        public double In_Entry102 { get; set; }
        public double In_Entry103 { get; set; }
        public double In_Entry104 { get; set; }
        public double In_Entry105 { get; set; }
        public double In_Entry106 { get; set; }
        public double In_Entry107 { get; set; }
        public double In_Entry108 { get; set; }
        public double In_Entry109 { get; set; }
        public double In_Entry110 { get; set; }
        public double In_Entry111 { get; set; }
        public double In_Entry112 { get; set; }
        public double In_Entry113 { get; set; }
        public double In_Entry114 { get; set; }
        public double In_Entry115 { get; set; }
        public double In_Entry116 { get; set; }
        public double In_Entry117 { get; set; }
        public double In_Entry118 { get; set; }
        public double In_Entry119 { get; set; }
        public double In_Entry120 { get; set; }
        public double In_Entry121 { get; set; }
        public double In_Entry122 { get; set; }
        public double In_Entry123 { get; set; }
        public double In_Entry124 { get; set; }
        public double In_Entry125 { get; set; }
        public double In_Entry126 { get; set; }
        public double In_Entry127 { get; set; }
        public double In_Entry128 { get; set; }
        public double In_Entry129 { get; set; }
        public double In_Entry130 { get; set; }
        public double In_Entry131 { get; set; }
        public double In_Entry132 { get; set; }
        public double In_Entry133 { get; set; }
        public double In_Entry134 { get; set; }
        public double In_Entry135 { get; set; }
        public double In_Entry136 { get; set; }
        public double In_Entry137 { get; set; }
        public double In_Entry138 { get; set; }
        public double In_Entry139 { get; set; }
        public double In_Entry140 { get; set; }
        public double In_Entry141 { get; set; }
        public double In_Entry142 { get; set; }
        public double In_Entry143 { get; set; }
        public double In_Entry144 { get; set; }
        public double In_Entry145 { get; set; }
        public double In_Entry146 { get; set; }
        public double In_Entry147 { get; set; }
        public double In_Entry148 { get; set; }
        public double In_Entry149 { get; set; }
        public double In_Entry150 { get; set; }
        public double In_Entry151 { get; set; }
        public double In_Entry152 { get; set; }
        public double In_Entry153 { get; set; }
        public double In_Entry154 { get; set; }
        public double In_Entry155 { get; set; }
        public double In_Entry156 { get; set; }
        public double In_Entry157 { get; set; }
        public double In_Entry158 { get; set; }
        public double In_Entry159 { get; set; }
        public double In_Entry160 { get; set; }
        public double In_Entry161 { get; set; }
        public double In_Entry162 { get; set; }
        public double In_Entry163 { get; set; }
        public double In_Entry164 { get; set; }
        public double In_Entry165 { get; set; }
        public double In_Entry166 { get; set; }
        public double In_Entry167 { get; set; }
        public double In_Entry168 { get; set; }
        public double In_Entry169 { get; set; }
        public double In_Entry170 { get; set; }
        public double In_Entry171 { get; set; }
        public double In_Entry172 { get; set; }
        public double In_Entry173 { get; set; }
        public double In_Entry174 { get; set; }
        public double In_Entry175 { get; set; }
        public double In_Entry176 { get; set; }
        public double In_Entry177 { get; set; }
        public double In_Entry178 { get; set; }
        public double In_Entry179 { get; set; }
        public double In_Entry180 { get; set; }
        public double In_Entry181 { get; set; }
        public double In_Entry182 { get; set; }
        public double In_Entry183 { get; set; }
        public double In_Entry184 { get; set; }
        public double In_Entry185 { get; set; }
        public double In_Entry186 { get; set; }
        public double In_Entry187 { get; set; }
        public double In_Entry188 { get; set; }
        public double In_Entry189 { get; set; }
        public double In_Entry190 { get; set; }
        public double In_Entry191 { get; set; }
        public double In_Entry192 { get; set; }
        public double In_Entry193 { get; set; }
        public double In_Entry194 { get; set; }
        public double In_Entry195 { get; set; }
        public double In_Entry196 { get; set; }
        public double In_Entry197 { get; set; }
        public double In_Entry198 { get; set; }
        public double In_Entry199 { get; set; }
        public double In_Entry200 { get; set; }

    }

}