// COMPILER GENERATED CODE
// THIS WILL BE OVERWRITTEN AT EACH GENERATION
// EDIT AT YOUR OWN RISK

using System.Runtime.CompilerServices;

namespace SSDQopenECA.Model.GPA
{
    [CompilerGenerated]
    public partial class Out_Data
    {
        //Modified by Tapas for Max Entries allowed=200
        public double Out_Entry1 { get; set; }
        public double Out_Entry2 { get; set; }
        public double Out_Entry3 { get; set; }
        public double Out_Entry4 { get; set; }
        public double Out_Entry5 { get; set; }
        public double Out_Entry6 { get; set; }
        public double Out_Entry7 { get; set; }
        public double Out_Entry8 { get; set; }
        public double Out_Entry9 { get; set; }
        public double Out_Entry10 { get; set; }
        public double Out_Entry11 { get; set; }
        public double Out_Entry12 { get; set; }
        public double Out_Entry13 { get; set; }
        public double Out_Entry14 { get; set; }
        public double Out_Entry15 { get; set; }
        public double Out_Entry16 { get; set; }
        public double Out_Entry17 { get; set; }
        public double Out_Entry18 { get; set; }
        public double Out_Entry19 { get; set; }
        public double Out_Entry20 { get; set; }
        public double Out_Entry21 { get; set; }
        public double Out_Entry22 { get; set; }
        public double Out_Entry23 { get; set; }
        public double Out_Entry24 { get; set; }
        public double Out_Entry25 { get; set; }
        public double Out_Entry26 { get; set; }
        public double Out_Entry27 { get; set; }
        public double Out_Entry28 { get; set; }
        public double Out_Entry29 { get; set; }
        public double Out_Entry30 { get; set; }
        public double Out_Entry31 { get; set; }
        public double Out_Entry32 { get; set; }
        public double Out_Entry33 { get; set; }
        public double Out_Entry34 { get; set; }
        public double Out_Entry35 { get; set; }
        public double Out_Entry36 { get; set; }
        public double Out_Entry37 { get; set; }
        public double Out_Entry38 { get; set; }
        public double Out_Entry39 { get; set; }
        public double Out_Entry40 { get; set; }
        public double Out_Entry41 { get; set; }
        public double Out_Entry42 { get; set; }
        public double Out_Entry43 { get; set; }
        public double Out_Entry44 { get; set; }
        public double Out_Entry45 { get; set; }
        public double Out_Entry46 { get; set; }
        public double Out_Entry47 { get; set; }
        public double Out_Entry48 { get; set; }
        public double Out_Entry49 { get; set; }
        public double Out_Entry50 { get; set; }
        public double Out_Entry51 { get; set; }
        public double Out_Entry52 { get; set; }
        public double Out_Entry53 { get; set; }
        public double Out_Entry54 { get; set; }
        public double Out_Entry55 { get; set; }
        public double Out_Entry56 { get; set; }
        public double Out_Entry57 { get; set; }
        public double Out_Entry58 { get; set; }
        public double Out_Entry59 { get; set; }
        public double Out_Entry60 { get; set; }
        public double Out_Entry61 { get; set; }
        public double Out_Entry62 { get; set; }
        public double Out_Entry63 { get; set; }
        public double Out_Entry64 { get; set; }
        public double Out_Entry65 { get; set; }
        public double Out_Entry66 { get; set; }
        public double Out_Entry67 { get; set; }
        public double Out_Entry68 { get; set; }
        public double Out_Entry69 { get; set; }
        public double Out_Entry70 { get; set; }
        public double Out_Entry71 { get; set; }
        public double Out_Entry72 { get; set; }
        public double Out_Entry73 { get; set; }
        public double Out_Entry74 { get; set; }
        public double Out_Entry75 { get; set; }
        public double Out_Entry76 { get; set; }
        public double Out_Entry77 { get; set; }
        public double Out_Entry78 { get; set; }
        public double Out_Entry79 { get; set; }
        public double Out_Entry80 { get; set; }
        public double Out_Entry81 { get; set; }
        public double Out_Entry82 { get; set; }
        public double Out_Entry83 { get; set; }
        public double Out_Entry84 { get; set; }
        public double Out_Entry85 { get; set; }
        public double Out_Entry86 { get; set; }
        public double Out_Entry87 { get; set; }
        public double Out_Entry88 { get; set; }
        public double Out_Entry89 { get; set; }
        public double Out_Entry90 { get; set; }
        public double Out_Entry91 { get; set; }
        public double Out_Entry92 { get; set; }
        public double Out_Entry93 { get; set; }
        public double Out_Entry94 { get; set; }
        public double Out_Entry95 { get; set; }
        public double Out_Entry96 { get; set; }
        public double Out_Entry97 { get; set; }
        public double Out_Entry98 { get; set; }
        public double Out_Entry99 { get; set; }
        public double Out_Entry100 { get; set; }
        public double Out_Entry101 { get; set; }
        public double Out_Entry102 { get; set; }
        public double Out_Entry103 { get; set; }
        public double Out_Entry104 { get; set; }
        public double Out_Entry105 { get; set; }
        public double Out_Entry106 { get; set; }
        public double Out_Entry107 { get; set; }
        public double Out_Entry108 { get; set; }
        public double Out_Entry109 { get; set; }
        public double Out_Entry110 { get; set; }
        public double Out_Entry111 { get; set; }
        public double Out_Entry112 { get; set; }
        public double Out_Entry113 { get; set; }
        public double Out_Entry114 { get; set; }
        public double Out_Entry115 { get; set; }
        public double Out_Entry116 { get; set; }
        public double Out_Entry117 { get; set; }
        public double Out_Entry118 { get; set; }
        public double Out_Entry119 { get; set; }
        public double Out_Entry120 { get; set; }
        public double Out_Entry121 { get; set; }
        public double Out_Entry122 { get; set; }
        public double Out_Entry123 { get; set; }
        public double Out_Entry124 { get; set; }
        public double Out_Entry125 { get; set; }
        public double Out_Entry126 { get; set; }
        public double Out_Entry127 { get; set; }
        public double Out_Entry128 { get; set; }
        public double Out_Entry129 { get; set; }
        public double Out_Entry130 { get; set; }
        public double Out_Entry131 { get; set; }
        public double Out_Entry132 { get; set; }
        public double Out_Entry133 { get; set; }
        public double Out_Entry134 { get; set; }
        public double Out_Entry135 { get; set; }
        public double Out_Entry136 { get; set; }
        public double Out_Entry137 { get; set; }
        public double Out_Entry138 { get; set; }
        public double Out_Entry139 { get; set; }
        public double Out_Entry140 { get; set; }
        public double Out_Entry141 { get; set; }
        public double Out_Entry142 { get; set; }
        public double Out_Entry143 { get; set; }
        public double Out_Entry144 { get; set; }
        public double Out_Entry145 { get; set; }
        public double Out_Entry146 { get; set; }
        public double Out_Entry147 { get; set; }
        public double Out_Entry148 { get; set; }
        public double Out_Entry149 { get; set; }
        public double Out_Entry150 { get; set; }
        public double Out_Entry151 { get; set; }
        public double Out_Entry152 { get; set; }
        public double Out_Entry153 { get; set; }
        public double Out_Entry154 { get; set; }
        public double Out_Entry155 { get; set; }
        public double Out_Entry156 { get; set; }
        public double Out_Entry157 { get; set; }
        public double Out_Entry158 { get; set; }
        public double Out_Entry159 { get; set; }
        public double Out_Entry160 { get; set; }
        public double Out_Entry161 { get; set; }
        public double Out_Entry162 { get; set; }
        public double Out_Entry163 { get; set; }
        public double Out_Entry164 { get; set; }
        public double Out_Entry165 { get; set; }
        public double Out_Entry166 { get; set; }
        public double Out_Entry167 { get; set; }
        public double Out_Entry168 { get; set; }
        public double Out_Entry169 { get; set; }
        public double Out_Entry170 { get; set; }
        public double Out_Entry171 { get; set; }
        public double Out_Entry172 { get; set; }
        public double Out_Entry173 { get; set; }
        public double Out_Entry174 { get; set; }
        public double Out_Entry175 { get; set; }
        public double Out_Entry176 { get; set; }
        public double Out_Entry177 { get; set; }
        public double Out_Entry178 { get; set; }
        public double Out_Entry179 { get; set; }
        public double Out_Entry180 { get; set; }
        public double Out_Entry181 { get; set; }
        public double Out_Entry182 { get; set; }
        public double Out_Entry183 { get; set; }
        public double Out_Entry184 { get; set; }
        public double Out_Entry185 { get; set; }
        public double Out_Entry186 { get; set; }
        public double Out_Entry187 { get; set; }
        public double Out_Entry188 { get; set; }
        public double Out_Entry189 { get; set; }
        public double Out_Entry190 { get; set; }
        public double Out_Entry191 { get; set; }
        public double Out_Entry192 { get; set; }
        public double Out_Entry193 { get; set; }
        public double Out_Entry194 { get; set; }
        public double Out_Entry195 { get; set; }
        public double Out_Entry196 { get; set; }
        public double Out_Entry197 { get; set; }
        public double Out_Entry198 { get; set; }
        public double Out_Entry199 { get; set; }
        public double Out_Entry200 { get; set; }
    }
}